# Generated by Django 2.0 on 2020-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='ding', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usersmessagedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=20)),
                ('loginstatus', models.CharField(max_length=20)),
                ('authsession', models.CharField(max_length=20)),
                ('nickname', models.CharField(default='ding', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('sex', models.CharField(default='', max_length=20)),
                ('age', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=20)),
                ('telephone', models.CharField(default='', max_length=20)),
                ('caseimg', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
