# Generated by Django 2.0 on 2020-02-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0002_usersmessagedb_testcase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usersmessagedb',
            new_name='usersmessagemysqldb',
        ),
    ]
