# Generated by Django 2.0 on 2020-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0003_auto_20200217_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='authsession',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='nickname',
            field=models.CharField(default='testname', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='openid',
            field=models.CharField(max_length=60),
        ),
    ]
