# Generated by Django 2.0 on 2020-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0004_auto_20200217_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmessagemysqldb',
            name='testcase',
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='caseimg',
            field=models.CharField(default='', max_length=50),
        ),
    ]
