# Generated by Django 2.0 on 2020-02-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0005_auto_20200217_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='authsession',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='caseimg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='loginstatus',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='openid',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='sex',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
