# Generated by Django 2.0 on 2020-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0007_auto_20200227_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='age',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='authsession',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='department',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='loginstatus',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='openid',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='sex',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
