# Generated by Django 2.0 on 2020-03-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0008_auto_20200303_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='case1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='case2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='case3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='case4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersmessagemysqldb',
            name='caseimg',
            field=models.CharField(default='', max_length=50),
        ),
    ]
